def test():
    pass


def failing_test():
    raise Exception()
